version: "3.7"
services:

    bffapi: 
        environment:
            - "ConnectionStrings:DefaultConnection=Server=bffdb;Database=BackendForFrontendDb;User Id=sa;Password=Jko3va-D9821jhsvGD"
            - "PRODUCT_MANAGEMENT_API_BASE_URL=http://pmapi:81/api/"
            - "ORDERING_API_BASE_URL=http://ordapi:82/api/"
            - "SITE_MANAGEMENT_API_BASE_URL=http://smapi:83/api/"
        image: ioanapatricia/bff.api:v1.0
        container_name: bff.api
        ports:
            - "5000:80"
        depends_on:
            - bffdb
            - pmapi
            - ordapi
            - pmdb
            - smapi
                    
    bffdb:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: bff.db
        ports:
            - "1434:1433"
        environment:
            - "SA_PASSWORD=Jko3va-D9821jhsvGD"
            - "ACCEPT_EULA=Y"
            
    pmapi: 
        environment:
            - "ConnectionStrings:DefaultConnection=Server=pmdb;Database=ProductManagementDb;User Id=sa;Password=Jko3va-D9821jhsvGD"
        image: ioanapatricia/pm.api:v1.0
        container_name: pm.api
        ports:
            - "5001:81"
        depends_on:
            - pmdb
        
    pmdb:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: pm.db
        ports:
            - "1435:1433"
        environment:
            - "SA_PASSWORD=Jko3va-D9821jhsvGD"
            - "ACCEPT_EULA=Y"
            
    ordapi: 
        image: ioanapatricia/ord.api:v1.0
        container_name: ord.api
        ports:
            - "5002:82"
    
    smapi: 
        image: ioanapatricia/sm.api:v1.0
        container_name: sm.api
        ports:
            - "5003:83"

    admclient: 
        image: ioanapatricia/adm.client:v1.0
        container_name: adm.client
        ports:
            - "8081:3000"
    ctmclient: 
        image: ioanapatricia/ctm.client:v1.0
        container_name: ctm.client
        ports:
            - "8080:3001"